version: '3'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - /redis_data:/data
    container_name: redis
    restart: always

  flask_api:
    image: hryanneco/flask_redis_set_get_api
    ports:
      - "80:80"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    container_name: flask_redis_set_get_api
    restart: always

